export const siteConfig = {
  name: 'BWIN Consultants',
  logo: '/assets/logo/bwin-logo.png',
  phone: '+880 1978 453907',
  phoneHref: 'tel:+8801978453907',
  email: 'info@bwinconsultants.com',
  address: 'Plot-1/2, Bijoy Rakeen City, NR2 Tower, Level-2, Unit-9, Block-D, Section-15, Mirpur, Dhaka-1216',
  social: {
    facebook: '#',
    x: '#',
    linkedin: '#',
  },
};

export const routes = {
  home: '/',
  aboutUs: '/about-us',
  articles: '/articles',
  bookACall: '/book-a-call',
  bootcamp: '/bootcamp',
  bundleOffer: '/bundle-offer',
  businessAutomation: '/business-automation',
  consultancy: '/consultancy',
  contactUs: '/contact-us',
  courseDetails: '/course-details',
  eLearning: '/e-learning',
  faq: '/faq',
  freeConsultation: '/free-consultation',
  getAFreeQuote: '/get-a-free-quote',
  jobSuccess: '/job-success',
  login: '/login',
  register: '/register',
  forgotPassword: '/forgot-password',
  privacyPolicy: '/privacy-policy',
  refundPolicy: '/refund-policy',
  skillDevelopment: '/skill-development',
  teams: '/teams',
  termsConditions: '/terms-conditions',
};
